# -*- coding: utf-8 -*-
"""Yet another copy of Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19pKX4-M-K1deLcEWqN_ecSk5Zsdf7x8V
"""

s1={1,1,2,2,2,3,3,3}
print(s1)
print(type(s1))

A = [4,5,6,7,8,9,0,6]

s2 = set(A)
print(s2)
print(type(s2))

s1 = {1,2,3,4,5}
s2 = {4,5,6,7,8}

s1.symmetric_difference(s2)

s1 = {1,2,3,4,5}
s2 = {1,2,3}

s2.issubset(s1)

s2.issuperset(s1)

str1 = "Welcome to aiml class"
print(str1)
str2 = "We started with python"
print(str2)
str3 = "This is an awesome class"
print(str3)

print(str1)
str1[5:10]

print(str1)
str1.split()

reviews = ["The product is awesome" , "Great Service"]
joined_string = " ".join(reviews)
joined_string

str5 = "Hello,How are you? "
str5

str5 = "I'M OKAY"
str5.lower

reviews = {
    "Reviews1": "The sdjfkhslk.jsfdlkxn,mnjz"
    "Reviews2": "sd,jchxgjfksjdghasdfncxksd,j"
    "reviews3": "jdkshnafweksdchjfmndkhsdkfjsamfb"

}

review_analysis = { }
for key, review in reviews.items( )

d1 = { "laddu": 1662, "saxena":26267,"psycc":9032}

